<?php require_once TEMPLATES . '/includes/cabecalho.phtml' ?>
<h1>Criar produto</h1>

<form action="">
    <div>
        <label for="nome-produto">Nome do produto</label>
        <input type="text" name="nome-produto" placeholder="Nome do produto" id="nome">
    </div>
    <div>
        <label for="descricao">Descrição do produto</label>
        <input type="text" name="descricao" placeholder="Descrição do produto" id="descricao">
    </div>
    <div>
        <label for="sobre">Sobre o produto</label>
        <textarea name="sobre" placeholder="Sobre o produto" id="sobre">
    </div>
    <div>
        <label for="preco">Preço do produto</label>
        <input type="text" name="preco" placeholder="Preço do produto" id="preco">
    </div>
</form>
<?php require_once TEMPLATES . '/includes/rodape.phtml' ?>
