<!-- Página inicial

< ?php var_dump(PRODUTOS); -->

<?php require_once TEMPLATES . '/includes/cabecalho.phtml' ?>

    <body>
        <?php foreach (PRODUTOS as $p) {
            echo $p['nome'] . '-' . $p['preco']; ?>
         <a href="<?php echo HOME ?>/?url=produto&produto=<?php echo $p['codigo'] . '&codigo=' . $p['codigo']?>">Ver produto</a><br><hr>
        <?php } ?>

        <?php require_once TEMPLATES . '/includes/rodape.phtml' ?>
